apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: new
        image: parshant09/yy
        ports:
        - containerPort: 80

